# Generated by Django 2.2.16 on 2022-07-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_Update_Post_Model_Created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='pub_date',
        ),
    ]
