# Generated by Django 2.2.16 on 2022-07-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_Update_Comment_Model_Meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='created',
        ),
    ]
